"""empty message

Revision ID: 2d7c8357d644
Revises: af37dc82768d
Create Date: 2020-10-29 09:23:21.829099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7c8357d644'
down_revision = 'af37dc82768d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_sales_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('shop_id', sa.String(length=64), nullable=True),
    sa.Column('bill_number', sa.String(length=64), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('product_description', sa.String(length=1024), nullable=True),
    sa.Column('sales_quantity', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_sales_data')
    # ### end Alembic commands ###
