"""shop sales data log

Revision ID: 319e8aa96efa
Revises: 2d7c8357d644
Create Date: 2020-10-30 16:07:43.257444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319e8aa96efa'
down_revision = '2d7c8357d644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_sales_data_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('shop_id', sa.String(length=64), nullable=True),
    sa.Column('bill_number', sa.String(length=64), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('product_description', sa.String(length=1024), nullable=True),
    sa.Column('sales_quantity', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('created_timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_sales_data_log')
    # ### end Alembic commands ###
