"""empty message

Revision ID: 8217afe681c9
Revises: 
Create Date: 2020-08-23 19:21:21.825992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8217afe681c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.String(length=64), nullable=False),
    sa.Column('category_name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('users',
    sa.Column('shop_id', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('shop_id')
    )
    op.create_table('catalog',
    sa.Column('product_id', sa.String(length=128), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('mrp', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.Column('size', sa.String(length=128), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('orders_received',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('pid', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['catalog.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.shop_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_inventory',
    sa.Column('product_id', sa.String(length=128), nullable=False),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.product_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_inventory')
    op.drop_table('orders_received')
    op.drop_table('catalog')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
