"""removed inventory relation with catalog

Revision ID: 8a45c04b369a
Revises: af82054b0298
Create Date: 2020-12-02 16:14:25.959047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a45c04b369a'
down_revision = 'af82054b0298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_inventory_ibfk_1', 'product_inventory', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('product_inventory_ibfk_2', 'product_inventory', 'catalog', ['product_id'], ['product_id'])
    # ### end Alembic commands ###
