"""removed foreign key relation between catalog and orders

Revision ID: af82054b0298
Revises: 319e8aa96efa
Create Date: 2020-12-02 13:36:10.680873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af82054b0298'
down_revision = '319e8aa96efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_received_ibfk_2', 'orders_received', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('orders_received_ibfk_2', 'orders_received', 'catalog', ['pid'], ['product_id'])
    # ### end Alembic commands ###
