"""discount in catalog

Revision ID: b69e20224ea1
Revises: 8a45c04b369a
Create Date: 2020-12-31 03:46:14.432133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b69e20224ea1'
down_revision = '8a45c04b369a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog', sa.Column('discount', sa.Float(), nullable=True))
    op.execute("UPDATE catalog SET discount = 0")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog', 'discount')
    # ### end Alembic commands ###
